// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI2mkADcJSUg8O3RbAKCnInd45PL1z4lI',
    appId: '1:111611203274:web:05f1224e1ef968135fee33',
    messagingSenderId: '111611203274',
    projectId: 'expense-tracker-7985d',
    authDomain: 'expense-tracker-7985d.firebaseapp.com',
    storageBucket: 'expense-tracker-7985d.appspot.com',
    measurementId: 'G-20BM43WQEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ybAQnvCQiDOpbEifjmhHvGz-1aRPkqU',
    appId: '1:111611203274:android:f650aa150fe6397d5fee33',
    messagingSenderId: '111611203274',
    projectId: 'expense-tracker-7985d',
    storageBucket: 'expense-tracker-7985d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHnGuFsYRw9bxWZgbdV6HOKdSyYudXiEY',
    appId: '1:111611203274:ios:7a768a44a46a32cb5fee33',
    messagingSenderId: '111611203274',
    projectId: 'expense-tracker-7985d',
    storageBucket: 'expense-tracker-7985d.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHnGuFsYRw9bxWZgbdV6HOKdSyYudXiEY',
    appId: '1:111611203274:ios:30ca8950cf22d5c85fee33',
    messagingSenderId: '111611203274',
    projectId: 'expense-tracker-7985d',
    storageBucket: 'expense-tracker-7985d.appspot.com',
    iosBundleId: 'com.example.expenseTracker.RunnerTests',
  );
}
